spring:
  application:
    name: FlightBooking

  datasource:
    url: jdbc:postgresql://localhost:5432/flight-booking-db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Dev-HikariPool
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update      # auto creates/updates tables locally
    show-sql: true          # print SQL in console
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:aiRFjw7nXXlOE2d9uEqZ8GriisT9VcxX9ZHvhvHXDJj}
      expiration: 86400000
      refresh-token:
        expiration: 604800000